### PR TITLE
more enhancements

### PR DESCRIPTION
**Pull request by mainakjas**
don't merge yet

### CODE REVIEW

**Comment by agramfort** [comment]
merge when you're happy. You're in charge ! :)

**Comment by dengemann** [comment]
@agramfort more changes staged ;) @mainakjas need to finalize them.

**Comment by mainakjas** [comment]
@dengemann : can you send me a wider mne-report screenshot?

I updated the bottom panel so that it has only the latest additions: https://www.dropbox.com/s/vrd1wtp6bmp2d1z/poster.pdf?dl=0

**Comment by agramfort** [comment]
Lgtm

**Comment by dengemann** [comment]
Can you send the link once more?

2015-05-26 16:43 GMT+02:00 Alexandre Gramfort <notifications@github.com>:

**Comment by dengemann** [comment]
(to the demo report)

2015-05-26 16:48 GMT+02:00 Denis-Alexander Engemann <
denis.engemann@gmail.com>:

**Comment by mainakjas** [comment]
this is it: https://www.dropbox.com/s/vrd1wtp6bmp2d1z/poster.pdf?dl=0

**Comment by dengemann** [comment]
nope the report, mainak. to make a screen shot.

2015-05-26 17:00 GMT+02:00 mainakjas <notifications@github.com>:

**Comment by mainakjas** [comment]
here you go: https://dl.dropboxusercontent.com/u/3915954/report.html

sorry, not used to multi-task :)

**Comment by mainakjas** [comment]
I added a small script to count the examples so that all future posterboys don't have to wonder how to count them.

**Comment by dengemann** [comment]
#posterboys :) 

Cool, useful!!

**Comment by agramfort** [comment]
LGTM

merge if you're done.

**Comment by agramfort** [comment]
thanks !

**Comment by dengemann** [comment]
@mainakjas https://www.dropbox.com/s/zvhkj8i7x8a17ws/Screenshot%202015-05-27%2013.24.48.png?dl=0 better?

**Comment by mainakjas** [comment]
yep, that does it for me. Comments addressed, merging and getting back to real PhD work :)

**Comment by agramfort** [comment]
:)

**Comment by dengemann** [comment]
Thanks Mainak,
I'm really happy with the poster now!

2015-05-27 15:07 GMT+02:00 Alexandre Gramfort <notifications@github.com>:

**Pull request merged**
