### PR TITLE
update poster for 2015

### PR DESCRIPTION
**Pull request by mainakjas**
sorry, doing it the traditional way making a PR :)

### CODE REVIEW

**Comment by agramfort** [comment]
let us know when ready to merge.

sharing the pdf on the mail thread as eg. dropbox link will help get quick feedback

**Comment by mainakjas** [comment]
I'll email everybody when we are at a more final state

in the meanwhile https://www.dropbox.com/s/vrd1wtp6bmp2d1z/poster.pdf?dl=0

**Comment by agramfort** [comment]
will do some cosmit in master

**Comment by agramfort** [comment]
done in master.

ready on my side.

**Comment by mainakjas** [comment]
cool, I sent the link to everyone for feedback.

**Pull request merged**
